name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install langgraph-cli
      - name: Install langgraph-cli
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: pip install -U langgraph-cli

      # Build the image using langgraph
      - name: Build image with langgraph
        run: langgraph build -t ghcr.io/${{ github.repository_owner }}/langgraph-server:latest
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Push image
        run: docker push ghcr.io/${{ github.repository_owner }}/langgraph-server:latest
